fix: handle unresolved nightly tag on first nightly release run

diff --git a/.github/workflows/nightly.yaml b/.github/workflows/nightly.yaml
--- a/.github/workflows/nightly.yaml
+++ b/.github/workflows/nightly.yaml
@@ -47,9 +47,12 @@ jobs:
         id: check_tags
         run: |
           curr_sha=$(git rev-parse HEAD)
-          prev_sha=$(git rev-parse ${{ env.PREV_TAG }})
+          prev_sha=$(git rev-parse ${{ env.PREV_TAG }} 2>/dev/null)
 
-          if [[ "$curr_sha" == "$prev_sha" ]]; then
+          if [[ $? -ne 0 ]]; then
+            echo "Tag ${{ env.PREV_TAG }} cannot be resolved. Continuing..."
+            echo "needs_build=true" >> $GITHUB_OUTPUT;
+          elif [[ "$curr_sha" == "$prev_sha" ]]; then
             echo "No changes since last nightly release. Exiting..."
             echo "needs_build=false" >> $GITHUB_OUTPUT;
           else
